# Generated by Django 3.1.7 on 2021-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_id',
            field=models.CharField(max_length=128, null=True, verbose_name='豆瓣id'),
        ),
    ]
